version: '3.8'

services:
  order-mysql:
    image: mysql:8
    container_name: order-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orderpass
      MYSQL_DATABASE: orderdb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  order-service:
    build: .
    depends_on:
      - order-mysql
    ports:
      - "8001:8001"
    environment:
      DB_HOST: order-mysql
      DB_USER: root
      DB_PASSWORD: orderpass
      DB_NAME: orderdb
      PORT: 8001
    command: ["./wait-for-it.sh", "order-mysql:3306", "--", "npm", "start"]

volumes:
  mysql_data:
